services:
  api:
    build: .
    container_name: piano-api
    restart: unless-stopped
    expose:
      - "3100"
    networks:
      - proxy
    volumes:
      - ./data:/app/data
      - ./media:/app/media
    env_file:
      - .env

networks:
  proxy:
    external: true
